name: BuildPushGoAppImage

env:
  GO_V:        "1.15"
  DOCKER_NAME: "go_app_image"

on:
  workflow_dispatch:
    inputs:
      Go_version:
        description: 'Go Version'
        required:    true
        default:     "1.15"
        type:        choice
        options:
        - '1.16'
        - '1.14'
        - '1.15'


  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git CheckOut
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_NAME }}:${{ env.GO_V }}
