name: GoWorkflow

on: 
  push:
    branches:
      - master
      
jobs:
  my_testing:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
        run : Echo "Hello World"
