name: GoWorkflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
        run : Echo "Hello World"
        
  my_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run : Echo "Hello World"
