name: RunGoapp

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      Go_version:
        description: 'Go Version'
        required: true
        default: 1.15
        type: choice
        options:
        - '1.16'
        - '1.14'
        - '1.15'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: CHECKOUT
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.Go_version }}

      - name: Build
        run : go build -v ./...

      - name: Run main.go
        run : go run main.go
        

