name: RunGoApp
env:
  GO_V: "1.15"
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      Go_version:
        description: 'Go Version'
        required: true
        default: "1.15"
        type: choice
        options:
        - '1.16'
        - '1.14'
        - '1.15'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: CHECKOUT
        uses: actions/checkout@v3

      - name: Run ls -la command
        run : ls -la

      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_V }}

      - name: Build
        run : go build -v ./...

      - name: Run main.go
        run : go run main.go
      - name: echo-default-env-variables
        run: |
                  echo "Home: ${HOME}"
                  echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
                  echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
                  echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
                  echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
                  echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
                  echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
                  echo "GITHUB_SHA: ${GITHUB_SHA}"
                  echo "GITHUB_REF: ${GITHUB_REF}"
                  echo "GITHUB_REF: ${GITHUB_RUN_NUMBER}"
        

