name: RunGoapp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: CHECKOUT
        uses: actions/checkout@v3
        
      - name: Run ls command
        run : ls -la 


